server:
  port: 8081
spring:

  zipkin:
    base-url: http://localhost:9411/

  sleuth:
    sampler:
      probability: 1

  application:
    name: apiproxy

management:
  metrics:
    export:
      influx:
        uri: http://localhost:8086
        db: services
        step: 5s

zuul:
  routes:
    citylocation:
      path: /citylcoationservice/**
      serviceId: citylcoationservice
      strip-prefix: true


    crimestoreservice:
      path: /crimestoreservice/**
      serviceId: crimestoreservice
      strip-prefix: true

    pointsaftyservice:
      path: /pointsafty/**
      serviceId: pointsaftyservice
      strip-prefix: true

    eventfiltering:
      path: /filter/**
      serviceid: crimefilteringservice
      strip-prefix: true