
spring:

  zipkin:
    base-url: http://localhost:9411/

  sleuth:
    sampler:
      probability: 1

  application:
    name: apiproxy


zuul:
  routes:
    citylocation:
      path: /citylcoationservice/**
      serviceId: citylcoationservice
      strip-prefix: true


    crimestoreservice:
      path: /crimestoreservice/**
      serviceId: crimestoreservice
      strip-prefix: true

    pointsaftyservice:
      path: /pointsafty/**
      serviceId: pointsaftyservice
      strip-prefix: true

    eventfiltering:
      path: /filter/**
      serviceid: crimefilteringservice
      strip-prefix: true