cassandra:
  contactPoints: 0.0.0.0
  port: 9042
  keyspace: crimestore
server:
  port: 8080

spring:

  zipkin:
    base-url: http://localhost:9411/

  sleuth:
    sampler:
      probability: 1

  application:
    name: crimestoreservice
  data:
    cassandra:
      port: 9042
      keyspace-name: crimestore
      jmx-enabled: false
      contact-points: 0.0.0.0
      repositories: com.akulinski.crimetivitystoreservice.core.repositories
      schema-action: recreate

  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}:${random.value}

      host: localhost
      port: 8500


kafka:
  bootstrapAddress: localhost:9092
  groupId: crtimestoreservice
