server:
  port: 8081

spring:

  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: crimetivitystoreservoice
      repositories:
        type: auto


jwt:
  secret: ${JWT_TOKEN:tomeczekwodeczka}
