version: '2'

services:

  crimetivitystoreservoice-mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - ./mongodbdata/:/data/db/

  pointsaftyservice-mongodb:
    image: mongo:latest
    volumes:
      - ./pointsaftyservice/:/data/db/

  redis:
    extends:
      service: redis
      file: redis.yaml


  zookeeper:
    extends:
      service: zookeeper
      file: ./kafka-docker/docker-compose-single-broker.yml
    ports:
      - "2181:2181"

  kafka:
    extends:
      service: kafka
      file: ./kafka-docker/docker-compose-single-broker.yml
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "DATA_REQUESTS:1:1,DATA_LOADS:1:1,LOAD_DATA_REQUESTS:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9092:9092"
  kafka-manager:
    extends:
      service: kafka-manager
      file: ./kafka-docker/docker-compose-single-broker.yml
  consul:
    extends:
      service: consul
      file: consul.yaml
    ports:
      - "8500:8500"

  storage:
    extends:
      service: storage
      file: docker-zipkin.yaml

  zipkin:
    extends:
      service: zipkin
      file: docker-zipkin.yaml
    depends_on:
      - storage

  crimetivity-apiproxy:
    build:
      context: ../apiproxy
    environment:
      - SPRING_ZIPKIN_BASEURL=http://zipkin:9411
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
    ports:
      - '8080:8080'


  crimetivity-citylocationservice:
    build:
      context: ../crimelocationservice

    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_ZIPKIN_BASEURL=http://zipkin:9411

  crimetivity-crimestoreservice:
    build:
      context: ../crimetivitystoreservice

    links:
      - crimetivitystoreservoice-mongodb
    depends_on:
      - crimetivitystoreservoice-mongodb
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATA_MONGODB_URI=mongodb://crimetivitystoreservoice-mongodb:27017
      - KAFKA_BOOTSTRAPADDRESS=kafka:9092
      - SPRING_ZIPKIN_BASEURL=http://zipkin:9411

  crimetivity-crimefilteringservice:
    build:
      context: ../crimefilteringservice

    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_ZIPKIN_BASEURL=http://zipkin:9411

  crimetivity-pointsaftyservice:
    build:
      context: ../pointsaftyservice

    links:
      - pointsaftyservice-mongodb
    depends_on:
      - pointsaftyservice-mongodb
    environment:
      - SPRING_ZIPKIN_BASEURL=http://zipkin:9411
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATA_MONGODB_URI=mongodb://pointsaftyservice-mongodb:27017
      - KAFKA_BOOTSTRAPADDRESS=kafka:9092
      - LOGSTASH_URL=logstash

volumes:
  consul_data:
    driver: local