version: '2'

services:
  nginx:
    image: 'bitnami/nginx:1.16'

    network_mode: bridge
    volumes:
      - '$PWD/nginx.conf:/etc/nginx/nginx.conf:rw'
      - '$PWD/logs:/logs:rw'
    ports:
      - '80:8080'
      - '9095:9095'