---
apiVersion: v1
kind: Service
metadata:
  name: crimestoreservice
  labels:
    app: crimetivity
spec:
  ports:
    - port: 8080
  selector:
    app: crimestoreservice
    tier: crimetivity
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: crimestoreservice
  labels:
    app: crimetivity
spec:
  selector:
    matchLabels:
      app: crimestoreservice
      tier: crimetivity
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: crimestoreservice
        tier: crimetivity
    spec:
      containers:
        - image: docker.pkg.github.com/akulinski/crimetivity/crimetivitystoreservice:0.0.2-SNAPSHOT-kb
          name: api-proxy
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://crimestoreservice-mongodb:27017"
            - name: KAFKA_BOOTSTRAPADDRESS
              value: "kafka:9092"
            - name: SPRING_ZIPKIN_BASEURL
              value: "http://zipkin:9411"
            - name: SERVER_PORT
              value: "8080"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
      imagePullSecrets:
        - name: regcred