---
apiVersion: v1
kind: Service
metadata:
  name: crimefilteringservice
  labels:
    app: crimetivity
spec:
  ports:
    - port: 8080
  selector:
    app: crimefilteringservice
    tier: crimetivity
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: crimefilteringservice
  labels:
    app: crimetivity
spec:
  selector:
    matchLabels:
      app: crimefilteringservice
      tier: crimetivity
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: crimefilteringservice
        tier: crimetivity
    spec:
      containers:
        - image: docker.pkg.github.com/akulinski/crimetivity/crimefilteringservice:0.0.3-SNAPSHOT-kb
          name: crimefilteringservice
          env:
            - name: SPRING_ZIPKIN_BASEURL
              value: "http://zipkin:9411"
            - name: SERVER_PORT
              value: "8080"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
      imagePullSecrets:
        - name: regcred