---
apiVersion: v1
kind: Service
metadata:
  name: pointsaftyservice
  labels:
    app: crimetivity
spec:
  ports:
    - port: 8080
  selector:
    app: pointsaftyservice
    tier: crimetivity
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: pointsaftyservice
  labels:
    app: crimetivity
spec:
  selector:
    matchLabels:
      app: pointsaftyservice
      tier: crimetivity
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pointsaftyservice
        tier: crimetivity
    spec:
      containers:
        - image: docker.pkg.github.com/akulinski/crimetivity/pointsaftyservice:0.0.9-SNAPSHOT-kb-1
          name: pointsaftyservice
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
            - name: KAFKA_BOOTSTRAPADDRESS
              value: "kafka:9092"
            - name: LOGSTASH_URL
              value: "logstash"
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://pointsaftyservice-mongodb:27017"
            - name: SPRING_ZIPKIN_BASEURL
              value: "http://zipkin:9411"
            - name: SERVER_PORT
              value: "8080"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
      imagePullSecrets:
        - name: regcred