apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka-cluster
spec:
  ports:
    - port: 6379
  selector:
    app: kafka
    tier: kafka-cluster
  clusterIP: None

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pv-claim
  labels:
    app: kafka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka-cluster
spec:
  selector:
    matchLabels:
      app: kafka
      tier: kafka-cluster
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kafka
        tier: kafka-cluster
    spec:
      containers:
        - image: wurstmeister/kafka
          name: kafka
          env:
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: kafka
            - name: KAFKA_CREATE_TOPICS
              value: "DATA_REQUESTS:1:1,DATA_LOADS:1:1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
          ports:
            - containerPort: 9092
              name: kafka
          volumeMounts:
            - mountPath: /var/lib/kafka/data
              name: kafka-storage

      volumes:
        - name: kafka-storage
          persistentVolumeClaim:
            claimName: kafka-pv-claim