apiVersion: v1
kind: Service
metadata:
  name: kafka-manager
  labels:
    app: kafka-manager
spec:
  ports:
    - port: 9000
  selector:
    app: kafka-manager
    tier: kafka-cluster
  clusterIP: None

---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: kafka-manager
  labels:
    app: kafka-cluster
spec:
  selector:
    matchLabels:
      app: kafka-manager
      tier: kafka-cluster
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kafka-manager
        tier: kafka-cluster
    spec:
      containers:
        - image: sheepkiller/kafka-manager:latest
          name: kafka-manager
          ports:
            - containerPort: 9000
              name: kafka-manager
          env:
            - name: ZK_HOSTS
              value: zookeeper:2181
            - name: APPLICATION_SECRET
              value: "letmein"
            - name: KM_ARGS
              value: "-Djava.net.preferIPv4Stack=true"