apiVersion: v1
kind: Service
metadata:
  name: zipkin
  labels:
    app: zipkin
spec:
  ports:
    - port: 9411
  selector:
    app: zipkin
    tier: zipkin
  clusterIP: None

---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: zipkin
  labels:
    app: zipkin
spec:
  selector:
    matchLabels:
      app: zipkin
      tier: zipkin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zipkin
        tier: zipkin
    spec:
      containers:
        - image: openzipkin/zipkin
          name: zipkin
          env:
            - name: STORAGE_TYPE
              value: "mysql"
            - name: MYSQL_HOST
              value: "zipkin-mysql"

          ports:
            - containerPort: 9411
              name: zipkin