google:
  maps:
    url: https://maps.googleapis.com/maps/api/geocode
    apiKey: AIzaSyD1bGMYE_p7IodXLjvCssk30_4hY-D83PM

server:
  port: 0


logging:
  level:
    root: DEBUG

spring:

  zipkin:
    base-url: http://localhost:9411/

  sleuth:
    sampler:
      probability: 1

  application:
    name: citylcoationservice
  redis:
    host: 127.0.0.1
    password:
    port: 6379


