google:
  maps:
    url: https://maps.googleapis.com/maps/api/geocode
    apiKey: AIzaSyD1bGMYE_p7IodXLjvCssk30_4hY-D83PM

server:
  port: 0

spring:
  application:
    name: citylcoationservice
  redis:
    host: 127.0.0.1
    password:
    port: 6379

  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}:${random.value}

      host: localhost
      port: 8500

