server:
  port: 0

spring:

  zipkin:
    base-url: http://localhost:9411/

  sleuth:
    sampler:
      probability: 1

  application:
    name: crimefilteringservice

  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}:${random.value}

      host: localhost
      port: 8500
