server:
  port: 0

spring:
  application:
    name: crimefilteringservice

  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}:${random.value}

      host: localhost
      port: 8500
